// Generated by `pnpm ext:configure` (scripts/generate-extension-config.mjs)
// from NEXT_PUBLIC_APP_URL — do not edit by hand. Committed with a null
// default (see below) so a fresh checkout's manifest.json always has a real
// file to load; `pnpm dev`/`pnpm build`/`pnpm ext:*` regenerate it with
// your actual instance's URL as an uncommitted local change, the same
// pattern this repo already uses for AGENTS.md (see AGENTS.md itself).
self.JOB_TRACKER_DEFAULT_APP_URL = "http://localhost:3005";
